apiVersion: management.loft.sh/v1
kind: Team
metadata:
  creationTimestamp: null
  name: staging
spec:
  clusterRoles:
  - name: loft-management-admin
  description: Staging Group
  displayName: SSO Group Staging
  groups:
  - staging
  username: staging
  access:
  - name: loft-access
    verbs:
    - get
    - bind
    subresources:
    - clusters
    teams:
    - staging
