apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: argocd-target-staging-us
  namespace: p-webapp-staging
spec:
  templateRef:
    name: virtual-cluster-template-production
    version: 1.0.0
  clusterRef:
    cluster: sedp-staging
  owner:
    user: adminuser
  displayName: argocd-target-staging-us
---
apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: argocd-target-staging-eu
  namespace: p-webapp-staging
spec:
  templateRef:
    name: virtual-cluster-template-production
    version: 1.0.0
  clusterRef:
    cluster: sedp-staging
  owner:
    user: adminuser
  displayName: argocd-target-staging-eu
---
apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: argocd-target-staging-asia
  namespace: p-webapp-staging
spec:
  templateRef:
    name: virtual-cluster-template-production
    version: 1.0.0
  clusterRef:
    cluster: sedp-staging
  owner:
    user: adminuser
  displayName: argocd-target-staging-asia
