apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sedp-demo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/rarnhart/argocd-sedp.git
      revision: HEAD
      files:
      - path: "appset/sedp/env-config/**/config.json"
  template:
    metadata:
      name: '{{.env}}'
    spec:
      # The project the application belongs to.
      project: default
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    spec:
      # The project the application belongs to.
      sources:
        - repoURL: registry-1.docker.io/rarnhart
          chart: my-chart
          targetRevision: {{.chart}}
          helm:
            valueFiles:
            - $values/appset/sedp/my-values/common-values.yaml
            - $values/appset/sedp/my-values/app-version/{{.version}}-values.yaml
            - $values/appset/sedp/my-values/env-type/{{.type}}-values.yaml
            - $values/appset/sedp/my-values/regions/{{.region}}-values.yaml
            - $values/appset/sedp/my-values/envs/{{.env}}-values.yaml
        - repoURL: 'https://github.com/rarnhart/argocd-sedp.git'
          targetRevision: HEAD
          ref: values
      destination:
      {{- if eq .version "dev" }}
        server: https://vcluster.sedp.tallturtle.network/kubernetes/project/webapp-{{.version}}/virtualcluster/argocd-target-dev
      {{- else }}
        server: https://vcluster.sedp.tallturtle.network/kubernetes/project/webapp-{{.version}}/virtualcluster/argocd-target-{{.env}}
      {{- end }}
        namespace: '{{.env}}'
