apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-http-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.environment }}.tallturtle.network
      secretName: tls-vcluster-platform
  rules:
    - host: {{ .Values.environment }}.tallturtle.network
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: simple-service
              port:
                name: https
