# Kubernetes settings
replicaCount: 1

# Environment settings
environment: dev-us

# Application settings
userInterfaceTheme: "light"
cacheSize: "1024kb"
gpuEnabled: "1"
pageLimit: "25"
sorting: "Ascending"
nBuckets: "24"
