apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  sources:
    - repoURL: https://github.com/kostis-codefresh/multi-sources-example.git
      path: my-chart
      targetRevision: HEAD
      helm:
        valueFiles:
        - $values/my-values/common-values.yaml          
        - $values/my-values/app-version/qa-values.yaml               
        - $values/my-values/env-type/non-prod-values.yaml  
        - $values/my-values/regions/us-values.yaml                
        - $values/my-values/envs/qa-values.yaml
    - repoURL: 'https://github.com/kostis-codefresh/multi-sources-example.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true